config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("website.urls")),
    path("gabarita-if/", include("gabarita_if.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('tinymce/', include('tinymce.urls')),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .views import *

app_name = "dashboard"

urlpatterns = [
    path("", index, name="index"),
    path("ajax-messages/", ajax_mensagens, name="ajax-mensagens"),
    path("questoes/", questoes, name="questoes"),
    path("ajax/questoes/", ajax_questoes, name="ajax-questoes"),
    path("avaliacoes/", avaliacoes, name="avaliacoes"),
    path("textos-de-apoio/", textos, name="textos"),
    path("usuarios/", usuarios, name="usuarios"),

    path("ajax/questao/remover/<int:id>/", ajax_remover_questao, name="ajax-remover-questao"),
    path("ajax/avaliacoes/<int:id>/remover/", ajax_remover_avaliacao, name="ajax-remover-avaliacao"),
    path("ajax/textos-de-apoio/<int:id>/remover/", ajax_remover_texto, name="ajax-remover-texto"),
    path("ajax/usuarios/<int:id>/remover/", ajax_remover_usuario, name="ajax-remover-usuario"),

    path("ajax/questoes/<int:id>/detalhar/", ajax_detalhar_questao, name="ajax-detalhar-questao"),
    path("ajax/avaliacoes/<int:id>/detalhar/", ajax_detalhar_avaliacao, name="ajax-detalhar-avaliacao"),
    path("ajax/textos/<int:id>/detalhar/", ajax_detalhar_texto, name="ajax-detalhar-texto"),
    path("ajax/usuarios/<int:id>/detalhar/", ajax_detalhar_usuario, name="ajax-detalhar-usuario"),
    
    path("ajax/questoes/<int:id>/editar/", ajax_editar_questao, name="ajax-editar-questao"),
    path("ajax/avaliacoes/<int:id>/editar/", ajax_editar_avaliacao, name="ajax-editar-avaliacao"),
    path("ajax/textos-de-apoio/<int:id>/editar/", ajax_editar_texto, name="ajax-editar-texto"),
    path("ajax/usuarios/<int:id>/editar/", ajax_editar_usuario, name="ajax-editar-usuario"),

    path("ajax/questoes/criar/", ajax_criar_questao, name="ajax-criar-questao"),
    path("ajax/avaliacoes/criar/", ajax_criar_avaliacao, name="ajax-criar-avaliacao"),
    path("ajax/textos-de-apoio/criar/", ajax_criar_texto, name="ajax-criar-texto"),
    path("ajax/usuarios/criar/", ajax_criar_usuario, name="ajax-criar-usuario"),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path("edit-profile/", views.edit_profile, name="edit_profile"),
    # Customizando a view de login
    # Redireciona pra LOGIN_REDIRECT se o usuário logado
    # tentar acessar a página de Login
    path(
        "login/", 
        auth_views.LoginView.as_view(
            redirect_authenticated_user=True
        ),
        name="login"
    ),
    # O urlpatterns testa na sequência, então ele vai
    # achar o "login/" customizado primeiro ali em cima
    # e desconsiderar o padrão que está abaixo.
    path("", include("django.contrib.auth.urls")),
]

gabarita_if/models.py
from django.db import models
import random
from django.conf import settings
from tinymce import models as tinymce_models
from django.utils.html import strip_tags


class Disciplina(models.Model):
    nome = models.CharField(max_length=20, unique=True)

    class Meta:
        ordering = ["nome"]

    def __str__(self):
        return self.nome


class Assunto(models.Model):
    nome = models.CharField(max_length=50)
    disciplina = models.ForeignKey(Disciplina, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ["nome"]

    def __str__(self):
        return self.nome


class Fonte(models.Model):
    nome = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ["nome"]
    
    def __str__(self):
        return self.nome


class Questao(models.Model):
    disciplina = models.ForeignKey(Disciplina, on_delete=models.PROTECT)
    assunto = models.ForeignKey(Assunto, on_delete=models.PROTECT)
    fonte = models.ForeignKey(Fonte, on_delete=models.PROTECT)
    dificuldade = models.CharField(max_length=10, choices=[("Fácil", "Fácil"), ("Média", "Média"), ("Difícil", "Difícil")])
    enunciado = tinymce_models.HTMLField()
    codigo = models.CharField(max_length=6, unique=True, editable=False, null=True, blank=True, verbose_name="Código")
    gabarito_comentado = tinymce_models.HTMLField()
    video_solucao = models.URLField(max_length=500, blank=True, null=True, verbose_name="Vídeo solução")
    alternativa_a = models.CharField(max_length=500, verbose_name="Alternativa A")
    alternativa_b = models.CharField(max_length=500, verbose_name="Alternativa B") 
    alternativa_c = models.CharField(max_length=500, verbose_name="Alternativa C")
    alternativa_d = models.CharField(max_length=500, verbose_name="Alternativa D")
    alternativa_correta = models.CharField(max_length=1, choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")])

    class Meta:
        verbose_name = "Questão"
        verbose_name_plural = "Questões"
    
    def __str__(self):
        enunciado = strip_tags(self.enunciado) # Remove o HTML do enunciado antes de retornar
        return enunciado[:50]

    @classmethod
    def _generate_unique_codigo(cls):
        while True:
            codigo = str(random.randint(0, 999999)).zfill(6)
            if not cls.objects.filter(codigo=codigo).exists():
                return codigo

    def save(self, *args, **kwargs):
        if not self.codigo:
            self.codigo = self._generate_unique_codigo()
        super().save(*args, **kwargs)
    
    @property
    def alternativas(self):
        return {
            "A": self.alternativa_a,
            "B": self.alternativa_b,
            "C": self.alternativa_c,
            "D": self.alternativa_d,
        }


class Comentario(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    texto = tinymce_models.HTMLField()
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Comentário"
        verbose_name_plural = "Comentários"

    def __str__(self):
        return f"{self.usuario} - Questão {self.questao.id}"


class Avaliacao(models.Model):
    titulo = models.CharField(max_length=50, verbose_name="Título")
    subtitulo = models.CharField(max_length=50, verbose_name="Subtítulo", blank=True, null=True)
    fonte = models.ForeignKey(Fonte, on_delete=models.CASCADE)
    ano = models.PositiveIntegerField()
    tipo = models.CharField(max_length=10, choices=[("Prova", "Prova"), ("Simulado", "Simulado")])
    questoes = models.ManyToManyField(Questao, verbose_name="Questões")

    class Meta:
        verbose_name = "Avaliação"
        verbose_name_plural = "Avaliações"

    def __str__(self):
        return f"{self.titulo} ({self.ano})"


class TextoApoio(models.Model):
    titulo = models.CharField(max_length=50, verbose_name="Título")
    texto = tinymce_models.HTMLField(blank=True, null=True)
    questoes = models.ManyToManyField(Questao, verbose_name="Questões")
    
    class Meta:
        verbose_name = "Texto de Apoio"
        verbose_name_plural = "Textos de Apoio"

    def __str__(self):
        return self.titulo


class Caderno(models.Model):
    nome = models.CharField(max_length=100)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    questoes = models.ManyToManyField(Questao, verbose_name="Questões")
    cor = models.CharField(max_length=7, default="#fff")

    def __str__(self):
        return self.nome
    
    @property
    def total_questoes(self):
        return self.questoes.count()

    @property
    def total_assuntos(self):
        return self.questoes.values("assunto").distinct().count()

    @property
    def questoes_resolvidas(self):
        return (self.questoes.filter(respostas__usuario=self.usuario).distinct().count())


class RespostaAvaliacao(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    avaliacao = models.ForeignKey(Avaliacao, on_delete=models.CASCADE, null=True, blank=True)
    finalizada = models.BooleanField()
    
    class Meta:
        verbose_name = "Resposta da Avaliação"
        verbose_name_plural = "Respostas das Avaliações"

    def __str__(self):
        avaliacao = self.avaliacao
        return f"{self.usuario} - {avaliacao}"


class RespostaQuestao(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE, related_name="respostas")
    alternativa_escolhida = models.CharField(max_length=1, choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")])
    acertou = models.BooleanField()
    tentativa = models.ForeignKey(RespostaAvaliacao, on_delete=models.CASCADE, null=True, blank=True)
    respondida_em = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Resposta da Questão"
        verbose_name_plural = "Respostas das Questões"

    def __str__(self):
        return f"{self.usuario} - Questão {self.questao.id} ({self.alternativa_escolhida})"

dashboard/forms.py
from django import forms
from gabarita_if.models import *


class QuestaoForm(forms.ModelForm):
    class Meta:
        model = Questao
        fields = "__all__"


class AvaliacaoForm(forms.ModelForm):
    class Meta:
        model = Avaliacao
        fields = "__all__"


class TextoApoioForm(forms.ModelForm):
    class Meta:
        model = TextoApoio
        fields = "__all__"

dashboard/views/avaliacao.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from dashboard.tables import AvaliacaoTabela
from django_tables2 import RequestConfig
from gabarita_if.models import Avaliacao
from dashboard.forms import AvaliacaoForm
from django.http import JsonResponse

@login_required
@permission_required("gabarita_if.add_avaliacao", raise_exception=True)
def avaliacoes(request):
    avaliacoes = Avaliacao.objects.all()
    tabela = AvaliacaoTabela(avaliacoes)
    RequestConfig(request, paginate={"per_page": 10}).configure(tabela)

    context = {
        "titulo_pagina": "Avaliações",
        "subtitulo_pagina": "Aqui você pode cadastrar os Exames de Seleção do IFRN e os Simuladões do Meta IFRN.",
        "nome": "avaliação",
        "url_criar": "dashboard:ajax-criar-avaliacao",
        "url_detalhar": "dashboard:ajax-detalhar-avaliacao",
        "url_editar": "dashboard:ajax-editar-avaliacao",
        "url_remover": "dashboard:ajax-remover-avaliacao",
        "tabela": tabela,
        "partial": "dashboard/partials/_tabela.html",
        "objects": avaliacoes,
    }
    
    return render(request, "listar.html", context)

@login_required
@permission_required("gabarita_if.add_avaliacao", raise_exception=True)
def ajax_criar_avaliacao(request):
    if request.method == "POST":
        form = AvaliacaoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Avaliação criada com sucesso!")
            return JsonResponse({"mensagem": "Avaliação criada com sucesso!"}, status=201)
        else:
            messages.error(request, "Falha ao criar avaliação!")
    else:
        form = AvaliacaoForm()
    
    return render(request, "criar.html", {"form": form})

@login_required
@permission_required("gabarita_if.view_avaliacao", raise_exception=True)
def ajax_detalhar_avaliacao(request, id):
    avaliacao = get_object_or_404(Avaliacao, id=id)
    fields = "__all__"
    safe_fields = []

    def get_fields():
        selected_fields = []
        no_check = not isinstance(fields, (list, tuple))
        for field in avaliacao._meta.fields:
            if no_check or field.name in fields:
                selected_fields.append(
                    {
                        "label": field.verbose_name,
                        "value": getattr(avaliacao, field.name),
                        "safe": True if field.name in safe_fields else False,
                    }
                )
        
        for field in avaliacao._meta.many_to_many:
            if no_check or field.name in fields:
                selected_fields.append({
                    "label": field.verbose_name,
                    "value": getattr(avaliacao, field.name).all(),
                    "safe": False,
                    "many": True,
                })

        return selected_fields
    
    context = {
        "nome": "avaliação",
        "object": avaliacao,
        "fields": get_fields()
    }

    return render(request, "detalhar.html", context)

@login_required
@permission_required("gabarita_if.change_avaliacao", raise_exception=True)
def ajax_editar_avaliacao(request, id):
    avaliacao = get_object_or_404(Avaliacao, id=id)
    if request.method == "POST":
        form = AvaliacaoForm(request.POST, request.FILES, instance=avaliacao)
        if form.is_valid():
            form.save()
            messages.success(request, "Avaliação atualizada com sucesso!")
            return JsonResponse({"mensagem": "Avaliação atualizada com sucesso!"}, status=200)
        else:
            messages.error(request, "Falha ao atualizar avaliação!")
    else:
        form = AvaliacaoForm(instance=avaliacao)

    context = {
        "url_voltar": "dashboard:avaliacoes",
        "form": form
    }

    return render(request, "editar.html", context)

@login_required
@permission_required("gabarita_if.delete_avaliacao", raise_exception=True)
def ajax_remover_avaliacao(request, id):
    avaliacao = get_object_or_404(Avaliacao, id=id)
    if request.method == "POST":
        avaliacao.delete()
        messages.success(request, "Avaliação removida com sucesso!")
        return redirect("dashboard:avaliacoes")
    else:
        context = {
            "object": avaliacao,
            "url_remover": "dashboard:remover-avaliacao"
        }

        return render(request, "remover.html", context)

templates/dashboard/partials/_acoes.html
<div class="d-flex gap-1">
<a href="{% url url_detalhar record.id %}" class="btn btn-read btn-detalhar">
  <i class="fa-solid fa-eye"></i>
</a>
<a href="{% url url_editar record.id %}" class="btn btn-update btn-editar">
  <i class="fa-solid fa-pen-to-square"></i>
</a>
<a href="{% url url_remover record.id %}" class="btn btn-delete btn-remover">
  <i class="fa-solid fa-trash-can"></i>
</a>
</div>

templates/dashboard/partials/_detalhar_questao.html
<div>
  <div class="row">
    <div class="col">
      <div class="card mb-4">
        <div class="card-body">
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Disciplina</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ questao.disciplina }}</p>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Assunto</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ questao.assunto }}</p>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Enunciado</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ questao.enunciado }}</p>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Gabarito Comentado</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ questao.gabarito_comentado }}</p>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Alternativas</p>
            </div>
            <div class="col-sm-9">
              {% for alternativa in questao.alternativa_set.all %}
              <div {% if alternativa.correta %} style="color: var(--primary-color)" {% endif %}>
                {{ alternativa.texto|truncatechars:20 }}
              </div>
              {% endfor %}
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Textos de Apoio</p>
            </div>
            <div class="col-sm-9">
              {% for texto_de_apoio in questao.texto_de_apoio.all %}
              <div>{{ texto_de_apoio.titulo|truncatechars:20 }}</div>
              {% empty %}
              <span> — </span>
              {% endfor %}
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Vídeo Solução</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ questao.video_solucao }}</p>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Prova</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ questao.prova.titulo|default:"—" }}</p>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Simulado</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ questao.simulado.titulo|default:"—" }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="rounded-3 mb-3">
        <div class="mb-0 d-flex align-items-top justify-content-between">
          <a href="{% url 'dashboard:questoes' %}" class="back-link"
            ><i class="fa-solid fa-arrow-left" style="margin-right: 3px"></i> Voltar para Questões
          </a>
          <div>
            <a href="{% url 'dashboard:editar-questao' questao.id %}" class="btn btn-update">
              <i class="fa-solid fa-pen-to-square"></i>
            </a>
            <button class="btn btn-delete" data-bs-toggle="modal" data-bs-target="#modal{{ questao.id }}">
              <i class="fa-solid fa-trash-can"></i>
            </button>
            {% include "remover.html" with object=questao url_remover="dashboard:remover-questao" %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/dashboard/partials/_detalhar_simulado.html
<div>
  <div class="row">
    <div class="col">
      <div class="card mb-4">
        <div class="card-body">
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Título</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ simulado.titulo }}</p>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Subtítulo</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ simulado.subtitulo }}</p>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Ano</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ simulado.ano }}</p>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Questões</p>
            </div>
            <div class="col-sm-9">
              {% if simulado.questao_set.all %}
              <ul class="text-muted mb-0">
                {% for questao in simulado.questao_set.all %}
                <li>{{ questao.id }}</li>
                {% endfor %}
              </ul>
              {% else %}
              <p class="text-muted mb-0">—</p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="rounded-3 mb-3">
        <div class="mb-0 d-flex align-items-top justify-content-between">
          <a href="{% url 'dashboard:simulados' %}" class="back-link"
            ><i class="fa-solid fa-arrow-left" style="margin-right: 3px"></i> Voltar para Simulados
          </a>
          <div>
            <a href="{% url 'dashboard:editar-simulado' simulado.id %}" class="btn btn-update">
              <i class="fa-solid fa-pen-to-square"></i>
            </a>
            <button class="btn btn-delete" data-bs-toggle="modal" data-bs-target="#modal{{ simulado.id }}">
              <i class="fa-solid fa-trash-can"></i>
            </button>
            {% include "remover.html" with object=simulado url_remover="dashboard:remover-simulado" %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/dashboard/partials/_detalhar_texto.html
<div>
  <div class="row">
    <div class="col">
      <div class="card mb-4">
        <div class="card-body">
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Título</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ texto.titulo }}</p>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Texto</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ texto.texto|default:"—" }}</p>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-sm-3 m-auto">
              <p class="mb-0 line-title">Imagem</p>
            </div>
            <div class="col-sm-9">
              {% if texto.imagem %} <img src="{{ texto.imagem.url|default:"—" }}" alt="" class="img-fluid" width="400">
              <p class="text-muted mb-0 mt-1 small">{{ texto.imagem }}</p>
              {% else %} — {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="rounded-3 mb-3">
        <div class="mb-0 d-flex align-items-top justify-content-between">
          <a href="{% url 'dashboard:textos' %}" class="back-link"
            ><i class="fa-solid fa-arrow-left" style="margin-right: 3px"></i> Voltar para Textos de Apoio
          </a>
          <div>
            <a href="{% url 'dashboard:editar-texto' texto.id %}" class="btn btn-update">
              <i class="fa-solid fa-pen-to-square"></i>
            </a>
            <button class="btn btn-delete" data-bs-toggle="modal" data-bs-target="#modal{{ texto.id }}">
              <i class="fa-solid fa-trash-can"></i>
            </button>
            {% include "remover.html" with object=texto url_remover="dashboard:remover-texto" %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/dashboard/partials/_form_questao.html
{% load crispy_forms_filters %}
<ul class="nav nav-tabs" id="questaoTabs" role="tablist">
  <li class="nav-item" role="presentation">
    <button
      class="nav-link active"
      id="dados-tab"
      data-bs-toggle="tab"
      data-bs-target="#dados"
      type="button"
      role="tab"
    >
      Dados da Questão
    </button>
  </li>
  <li class="nav-item" role="presentation">
    <button
      class="nav-link"
      id="avaliacao-tab"
      data-bs-toggle="tab"
      data-bs-target="#avaliacao"
      type="button"
      role="tab"
    >
      Alternativas
    </button>
  </li>
  <li class="nav-item" role="presentation">
    <button
      class="nav-link"
      id="resolucao-tab"
      data-bs-toggle="tab"
      data-bs-target="#resolucao"
      type="button"
      role="tab"
    >
      Resoluções
    </button>
  </li>
</ul>

<div class="tab-content border border-top-0 rounded-bottom" id="questaoTabsContent" style="padding: 20px">
  <div class="tab-pane fade show active" id="dados" role="tabpanel">
    {{ form.disciplina|as_crispy_field }} 
    {{ form.assunto|as_crispy_field }}
    {{ form.dificuldade|as_crispy_field }}
    {{ form.fonte|as_crispy_field }}
    {{ form.enunciado|as_crispy_field }}
  </div>

  <div class="tab-pane fade" id="avaliacao" role="tabpanel">
    <p>Marque a alternativa correta.</p>
    <!-- Alternativa A -->
    <div class="mb-3">
      <div class="d-flex align-items-center gap-3 m-auto flex-grow-1">
        <label class="fw-semibold text-lg cursor-pointer">A)</label>
        <input class="form-check-input custom-radio" type="radio" name="alternativa_correta" value="A" id="alt_a_radio"
        {% if form.alternativa_correta.value == "A" %}checked{% endif %}> <input type="text" name="alternativa_a"
        class="form-control" placeholder="Digite a alternativa A" value="{{ form.alternativa_a.value|default:"" }}" />
      </div>
    </div>

    <!-- Alternativa B -->
    <div class="mb-3">
      <div class="d-flex align-items-center gap-3 m-auto flex-grow-1">
        <label class="fw-semibold text-lg cursor-pointer">B)</label>
        <input class="form-check-input custom-radio" type="radio" name="alternativa_correta" value="B" id="alt_b_radio"
        {% if form.alternativa_correta.value == "B" %}checked{% endif %}> <input type="text" name="alternativa_b"
        class="form-control" placeholder="Digite a alternativa B" value="{{ form.alternativa_b.value|default:"" }}" />
      </div>
    </div>

    <!-- Alternativa C -->
    <div class="mb-3">
      <div class="d-flex align-items-center gap-3 m-auto flex-grow-1">
        <label class="fw-semibold text-lg cursor-pointer">C)</label>
        <input class="form-check-input custom-radio" type="radio" name="alternativa_correta" value="C" id="alt_c_radio"
        {% if form.alternativa_correta.value == "C" %}checked{% endif %}> <input type="text" name="alternativa_c"
        class="form-control" placeholder="Digite a alternativa C" value="{{ form.alternativa_c.value|default:"" }}" />
      </div>
    </div>

    <!-- Alternativa D -->
    <div>
      <div class="d-flex align-items-center gap-3 m-auto flex-grow-1">
        <label class="fw-semibold text-lg cursor-pointer">D)</label>
        <input class="form-check-input custom-radio" type="radio" name="alternativa_correta" value="D" id="alt_d_radio"
        {% if form.alternativa_correta.value == "D" %}checked{% endif %}> <input type="text" name="alternativa_d"
        class="form-control" placeholder="Digite a alternativa D" value="{{ form.alternativa_d.value|default:"" }}" />
      </div>
    </div>
  </div>

  <div class="tab-pane fade" id="resolucao" role="tabpanel">
    {{ form.gabarito_comentado|as_crispy_field }} 
    {{ form.video_solucao|as_crispy_field }}
  </div>
</div>

{% block scripts %}
<script>
  $("#id_fonte").select2();
  $("#id_dificuldade").select2();
  $("#id_status").select2();
  $("#id_disciplina").select2();
  $("#id_assunto").select2();
</script>
{% endblock %}