config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("website.urls")),
    path("gabarita-if/", include("gabarita_if.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('tinymce/', include('tinymce.urls')),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path("edit-profile/", views.edit_profile, name="edit_profile"),
    # Customizando a view de login
    # Redireciona pra LOGIN_REDIRECT se o usuário logado
    # tentar acessar a página de Login
    path(
        "login/", 
        auth_views.LoginView.as_view(
            redirect_authenticated_user=True
        ),
        name="login"
    ),
    # O urlpatterns testa na sequência, então ele vai
    # achar o "login/" customizado primeiro ali em cima
    # e desconsiderar o padrão que está abaixo.
    path("", include("django.contrib.auth.urls")),
]

usuarios/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "usuarios"

urlpatterns = [
    path("cadastro/", views.cadastro, name="cadastro"),
    path("perfil/", views.perfil, name="perfil"),
    path("editar-perfil/", views.editar_perfil, name="editar-perfil"),
    # Customizando a view de login
    # Redireciona pra LOGIN_REDIRECT se o usuário logado
    # tentar acessar a página de Login
    path(
        "login/", 
        auth_views.LoginView.as_view(
            redirect_authenticated_user=True
        ),
        name="login"
    ),
    # O urlpatterns testa na sequência, então ele vai
    # achar o "login/" customizado primeiro ali em cima
    # e desconsiderar o padrão que está abaixo.
    path("", include("django.contrib.auth.urls")),
]

website/urls.py
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path("", views.index, name="index"),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render
from .models import *

def index(request):
    return render(request, 'website/index.html')

templates/website/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Gabarita IF - Plataforma de Questões</title>
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/32b23e8fdf.js" crossorigin="anonymous"></script>
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&family=Montserrat:wght@300;400;500;700;800&display=swap"
      rel="stylesheet"
    />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css" />
    <!-- CSS Principal -->
    <link rel="stylesheet" href="{% static 'website/css/styles.css' %}" />

    <!-- Animações -->
    <style>
      /* cards */
      .icon-box {
        transition: transform .25s ease, box-shadow .25s ease;
      }
      .icon-box:hover {
        transform: translateY(-6px);
        box-shadow: 0px 12px 22px rgba(0,0,0,0.20);
      }

      /* negocinho do instagram e wpp */
      .footer-col .fa-stack {
        transition: transform .25s ease;
      }
      .footer-col .fa-stack:hover {
        transform: rotate(15deg) scale(1.1);
      }
    </style>

  </head>
  <body data-bs-spy="scroll" data-bs-target="#navbarExample">
    <!-- Navigation -->
    <nav id="navbarExample" class="navbar navbar-expand-lg fixed-top navbar-light" aria-label="Main navigation">
      <div class="container">
        <!-- Image Logo -->
        <a class="navbar-brand logo-image" href="{% url 'website:index' %}"
          ><img src="{% static 'assets/img/logo_blue.svg' %}" class="img-fluid" alt="alternative"
        /></a>
        <button
          class="navbar-toggler p-0 border-0"
          type="button"
          id="navbarSideCollapse"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav ms-auto navbar-nav-scroll">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#header">Início</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#sobre">Sobre</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#funcionalidades">Funcionalidades</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#experimente">Experimente</a>
            </li>
          </ul>
          <span class="nav-item">
            <a class="btn-outline-sm btn-outline-primary btn" href="{% url 'usuarios:login' %}">Entrar</a>
          </span>
        </div>
      </div>
    </nav>

    <header id="header" class="header">
      <div class="container">
        <div class="row">
          <div class="col-lg-5">
            <div class="text-container">
              <h1 class="h1-large">Quer passar no IFRN? <span class="replace-me">cola na gente</span></h1>
              <p class="p-large">
                O Gabarita IF é a plataforma feita para quem quer estudar de forma leve, organizada e eficiente.
                Gabarite a prova e conquiste seu lugar no IFRN!
              </p>
              <a class="btn-solid-lg btn btn-secondary" href="{% url 'usuarios:login' %}">Comece Já!</a>
            </div>
          </div>
          <div class="col-lg-7">
            <div class="image-container">
              <img class="img-fluid" src="{% static 'assets/img/sla.svg' %}" alt="alternative" />
            </div>
          </div>
        </div>
      </div>
    </header>

    <div id="sobre" class="basic-1 bg-gray">
      <div class="container">
        <div class="row d-flex align-items-center">
          <div class="col-lg-6 col-xl-7">
            <div class="image-container">
              <img class="img-fluid" src="{% static 'assets/img/sobre.svg' %}" alt="alternative" />
            </div>
          </div>
          <div class="col-lg-6 col-xl-5">
            <div class="text-container m-0">
              <h1 style="margin-bottom: 8px">Sobre</h1>
              <h4 style="margin-bottom: 30px; font-family: 'Caveat'; font-size: 32px; color: var(--primary-color)" ;>
                De federais para futuros federais
              </h4>
              <p class="m-0" style="text-align: justify">
                Gabarita IF é um sistema educacional desenvolvido para
                <strong
                  >apoiar estudantes na preparação para o Exame de Seleção do Instituto Federal de Educação, Ciência e
                  Tecnologia do Rio Grande do Norte (IFRN)</strong
                >. O software mantém uma base de dados com questões de processos seletivos anteriores divulgados pelo
                IFRN e disponibiliza todos os simuladões já realizados pelo Meta IFRN. <br /><br />Esta plataforma é
                resultado da elaboração de um projeto de pesquisa realizado na disciplina intitulada "Desenvolvimento de
                Projeto Integrador" do curso Técnico Integrado ao Ensino Médio de Informática para Internet do IFRN –
                Campus São Paulo do Potengi.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <section id="funcionalidades" class="about section">
      <div class="container" data-aos="fade-up" data-aos-delay="100">
        <div class="row align-items-xl-center gy-5">
          <div class="col-xl-5 content">
            <h1 style="color: white">Todas as questões que você precisa, em um só lugar.</h1>
            <h4
              style="
                margin-bottom: 30px;
                font-family: 'Caveat';
                font-size: 32px;
                color: var(--secondary-color);
                line-height: 2.5rem;
              "
            >
              Estatísticas em tempo real e muito mais para transformar sua rotina de estudos
            </h4>
          </div>
          <div class="col-xl-7">
            <div class="row gy-4 icon-boxes" style="padding-left: 4rem">
              <div class="col-md-6" data-aos="fade-up" data-aos-delay="400">
                <div class="icon-box" style="background: var(--secondary-color)">
                  <i class="fa-solid fa-star"></i>
                  <h5 style="color: var(--bs-white)">Uma ferramenta fácil de usar</h5>
                  <p style="color: var(--bs-white)">
                    para realizar provas, simulados e montar cadernos de questões sem complicação
                  </p>
                </div>
              </div>
              <div class="col-md-6" data-aos="fade-up" data-aos-delay="200">
                <div class="icon-box">
                  <i class="fa-solid fa-circle-check"></i>
                  <h5>Questões de todos os Exames de Seleção do IFRN</h5>
                  <p>para você não perder tempo procurando por questões de qualidade</p>
                </div>
              </div>
              <div class="col-md-6" data-aos="fade-up" data-aos-delay="300">
                <div class="icon-box">
                  <i class="fa-solid fa-magnifying-glass"></i>
                  <h5>Busque exatamente o que você precisa</h5>
                  <p>com recursos de filtragem para encontrar as questões certas</p>
                </div>
              </div>
              <div class="col-md-6" data-aos="fade-up" data-aos-delay="500">
                <div class="icon-box" style="background: var(--secondary-color)">
                  <i class="fa-solid fa-chart-pie"></i>
                  <h5 style="color: var(--bs-white)">Estatísticas detalhadas</h5>
                  <p style="color: var(--bs-white)">para você acompanhar seu desempenho de perto</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <div id="experimente" class="basic-1 bg-gray">
      <div class="container">
        <div class="row d-flex align-items-center">
          <div class="col-lg-6 col-xl-7">
            <div class="image-container" style="margin-right: 4rem">
              <img
                class="img-fluid"
                style="width: 100%"
                src="{% static 'assets/img/gabarita.svg' %}"
                alt="alternative"
              />
            </div>
            <!-- end of image-container -->
          </div>
          <div class="col-lg-6 col-xl-5">
            <div class="text-container m-0">
              <h1 style="margin-bottom: 8px">Experimente o Gabarita do seu jeito</h1>
              <h4
                style="
                  margin-bottom: 30px;
                  font-family: 'Caveat';
                  font-size: 32px;
                  color: var(--primary-color);
                  line-height: 2.5rem;
                "
                ;
              >
                Na tela do seu computador ou na palma da sua mão
              </h4>
              <p class="m-0">
                Nossa plataforma foi desenvolvida para
                <strong>ser simples, intuitiva e funcionar perfeitamente em qualquer tela.</strong>
              </p>
            </div>
            <!-- end of text-container -->
          </div>
          <!-- end of col -->

          <!-- end of col -->
        </div>
        <!-- end of row -->
      </div>
      <!-- end of container -->
    </div>

    <section id="clients" class="clients section">
      <div class="container" data-aos="fade-up">
        <div class="row gy-4">
          <div class="col-lg-6 client-logo text-center">
            <a href="https://metaifrn.com/">
              <img src="{% static 'assets/img/logo_meta.png' %}" class="img-fluid" width="205" alt="Meta IFRN" />
            </a>
          </div>
          <div class="col-lg-6 client-logo text-center">
            <a href="https://portal.ifrn.edu.br/campus/sao-paulo-do-potengi/">
              <img src="{% static 'assets/img/logo_ifrn.png' %}" class="img-fluid" alt="IFRN" />
            </a>
          </div>
        </div>
      </div>
    </section>

    <footer>
      <div class="container">
        <div class="row">
          <div class="row">
            <div class="footer-col first col">
              <h4 style="color: var(--primary-color) !important">
                Seu estudo organizado <br />
                em um <span style="font-family: 'Caveat', cursive; color: white; font-size: 32px">único lugar</span>.
              </h4>
              <img
                src="{% static 'assets/img/logo_white.svg' %}"
                alt="Gabarita IF"
                class="img-fluid mt-2"
                width="210"
              />
            </div>

            <div class="footer-col third col text-end">
              <span class="fa-stack">
                <a href="https://api.whatsapp.com/send?phone=5584996596574" target="_blank" aria-label="WhatsApp">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-whatsapp fa-stack-1x"></i>
                </a>
              </span>
              <span class="fa-stack">
                <a href="https://www.instagram.com/gabaritaif/" target="_blank" aria-label="Instagram">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-instagram fa-stack-1x"></i>
                </a>
              </span>
              {% comment %}
              <!-- end of footer-col -->
              <h6 class="mt-2">Links</h6>
              <ul class="list-unstyled li-space-lg p-small">
                <li>
                  <a href="terms.html">Termos de Uso</a>
                </li>
                <li>
                  <a href="privacy.html">Política de Privacidade</a>
                </li>
              </ul>
            </div>
            {% endcomment %}
          </div>
        </div>
      </div>
    </footer>

    <!-- Copyright -->
    <div class="copyright py-4" style="background: var(--secondary-dark) !important">
      <div class="container">
        <div class="row">
          <div class="col">
            <p class="p-small m-0">Copyright © 2025 Gabarita IF</p>
          </div>
        </div>
      </div>
    </div>

    <button onclick="topFunction()" id="myBtn">
      <img src="{% static 'assets/img/up-arrow.png' %}" alt="Voltar ao topo" />
    </button>

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'website/js/scripts.js' %}"></script>
  </body>
</html>