config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("website.urls")),
    path("gabarita-if/", include("gabarita_if.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('tinymce/', include('tinymce.urls')),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .views import *

app_name = "dashboard"

urlpatterns = [
    path("", index, name="index"),
    path("ajax-messages/", ajax_mensagens, name="ajax-mensagens"),
    path("questoes/", questoes, name="questoes"),
    path("ajax/questoes/", ajax_questoes, name="ajax-questoes"),
    path("avaliacoes/", avaliacoes, name="avaliacoes"),
    path("textos-de-apoio/", textos, name="textos"),
    path("usuarios/", usuarios, name="usuarios"),

    path("ajax/questao/remover/<int:id>/", ajax_remover_questao, name="ajax-remover-questao"),
    path("ajax/avaliacoes/<int:id>/remover/", ajax_remover_avaliacao, name="ajax-remover-avaliacao"),
    path("ajax/textos-de-apoio/<int:id>/remover/", ajax_remover_texto, name="ajax-remover-texto"),
    path("ajax/usuarios/<int:id>/remover/", ajax_remover_usuario, name="ajax-remover-usuario"),

    path("ajax/questoes/<int:id>/detalhar/", ajax_detalhar_questao, name="ajax-detalhar-questao"),
    path("ajax/avaliacoes/<int:id>/detalhar/", ajax_detalhar_avaliacao, name="ajax-detalhar-avaliacao"),
    path("ajax/textos/<int:id>/detalhar/", ajax_detalhar_texto, name="ajax-detalhar-texto"),
    path("ajax/usuarios/<int:id>/detalhar/", ajax_detalhar_usuario, name="ajax-detalhar-usuario"),
    
    path("ajax/questoes/<int:id>/editar/", ajax_editar_questao, name="ajax-editar-questao"),
    path("ajax/avaliacoes/<int:id>/editar/", ajax_editar_avaliacao, name="ajax-editar-avaliacao"),
    path("ajax/textos-de-apoio/<int:id>/editar/", ajax_editar_texto, name="ajax-editar-texto"),
    path("ajax/usuarios/<int:id>/editar/", ajax_editar_usuario, name="ajax-editar-usuario"),

    path("ajax/questoes/criar/", ajax_criar_questao, name="ajax-criar-questao"),
    path("ajax/avaliacoes/criar/", ajax_criar_avaliacao, name="ajax-criar-avaliacao"),
    path("ajax/textos-de-apoio/criar/", ajax_criar_texto, name="ajax-criar-texto"),
    path("ajax/usuarios/criar/", ajax_criar_usuario, name="ajax-criar-usuario"),
]

gabarita_if/urls.py
from django.urls import path
from .views import *

app_name = "gabarita_if"

urlpatterns = [
    path("redirecionar/", redirecionar, name="redirecionar"),
    path("", index, name="index"),
    path("questoes/", questoes, name="questoes"),
    path("avaliacoes/", avaliacoes, name="avaliacoes"),
    path("avaliacoes/<int:id>/responder/", responder_avaliacao, name="responder-avaliacao"),
    path("avaliacoes/<int:id>/feedback/", ver_feedback_avaliacao, name="ver-feedback-avaliacao"),
    path("cadernos/", cadernos, name="cadernos"),
    path("ajax/cadernos/criar/", ajax_criar_caderno, name="ajax-criar-caderno"),
    path("cadernos/<int:id>/detalhar/", detalhar_caderno, name="detalhar-caderno"),
    path("ajax/cadernos/<int:id>/editar/", ajax_editar_caderno, name="ajax-editar-caderno"),
    path("ajax/cadernos/<int:id>/remover/", ajax_remover_caderno, name="ajax-remover-caderno"),
    path("meu-desempenho/", meu_desempenho, name="meu-desempenho")
]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path("edit-profile/", views.edit_profile, name="edit_profile"),
    # Customizando a view de login
    # Redireciona pra LOGIN_REDIRECT se o usuário logado
    # tentar acessar a página de Login
    path(
        "login/", 
        auth_views.LoginView.as_view(
            redirect_authenticated_user=True
        ),
        name="login"
    ),
    # O urlpatterns testa na sequência, então ele vai
    # achar o "login/" customizado primeiro ali em cima
    # e desconsiderar o padrão que está abaixo.
    path("", include("django.contrib.auth.urls")),
]

usuarios/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "usuarios"

urlpatterns = [
    path("cadastro/", views.cadastro, name="cadastro"),
    path("perfil/", views.perfil, name="perfil"),
    path("editar-perfil/", views.editar_perfil, name="editar-perfil"),
    # Customizando a view de login
    # Redireciona pra LOGIN_REDIRECT se o usuário logado
    # tentar acessar a página de Login
    path(
        "login/", 
        auth_views.LoginView.as_view(
            redirect_authenticated_user=True
        ),
        name="login"
    ),
    # O urlpatterns testa na sequência, então ele vai
    # achar o "login/" customizado primeiro ali em cima
    # e desconsiderar o padrão que está abaixo.
    path("", include("django.contrib.auth.urls")),
]

website/urls.py
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path("", views.index, name="index"),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="pt-BR">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Gabarita IF - Plataforma de Questões</title>
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/32b23e8fdf.js" crossorigin="anonymous"></script>
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
      rel="stylesheet"
    />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
      crossorigin="anonymous"
    />
    <!-- Core theme CSS -->
    <link rel="stylesheet" href="{% static 'gabarita_if/css/styles.css' %}" />
  </head>
  <body class="sb-nav-fixed">
    {% if show_splash %}
    <div id="splash-screen">
      <img src="{% static 'assets/img/logo_blue.svg' %}" alt="Logo Gabarita IF" class="splash-logo" />
    </div>
    {% endif %}

    <div id="main-content">
      <nav class="sb-topnav navbar navbar-expand">
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-lg-0" id="sidebarToggle" href="#!">
          <i class="fas fa-bars"></i>
        </button>
        <!-- Navbar Brand-->
        {% if request.user.is_superuser %}
        <a class="navbar-brand" href="{% url 'dashboard:index' %}">
          <img src="{% static 'assets/img/logo_blue.svg' %}" alt="Logo Azul" class="img-fluid"
        /></a>
        {% else %}
        <a class="navbar-brand" href="{% url 'gabarita_if:index' %}">
          <img src="{% static 'assets/img/logo_blue.svg' %}" alt="Logo Azul" class="img-fluid"
        /></a>
        {% endif %}
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto">
          <li class="nav-item dropdown">
            <a id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {% if request.user.avatar %}
              <img src="{{ request.user.avatar.url }}" alt="Avatar de {{ username }}" class="user-image" />
              {% else %}
              <img src="{% static 'assets/img/avatar.png' %}" alt="Avatar padrão" class="user-image" />
              {% endif %}
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><h6 class="dropdown-header">Olá, {{ user.username }}!</h6></li>
              <li><a class="dropdown-item" href="{% url 'usuarios:perfil' %}">Perfil</a></li>
              <li><a class="dropdown-item" href="{% url 'password_change' %}">Alterar Senha</a></li>
              <li><a class="dropdown-item" href="{% url 'website:index' %}">Página inicial</a></li>
              <li>
                <form method="POST" action="{% url 'logout' %}" class="dropdown-item">
                  {% csrf_token %}
                  <input type="submit" style="all: unset; width: 100%" value="Sair" />
                </form>
              </li>
            </ul>
          </li>
        </ul>
      </nav>

      <div id="div-mensagens">{% include 'partials/_messages.html' %}</div>

      <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
          <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
              <div class="nav">
                <!-- Admin Section -->
                {% if request.user.is_superuser %}
                <div class="sb-sidenav-menu-heading">Área do admin</div>
                <a
                  class="nav-link {% if request.resolver_match and request.resolver_match.namespace == 'dashboard' and request.resolver_match.url_name == 'index' %}active{% endif %}"
                  href="{% url 'dashboard:index' %}"
                >
                  <div class="sb-nav-link-icon"><i class="fa-solid fa-gauge-high"></i></div>
                  Dashboard
                </a>
                <a
                  class="nav-link collapsed"
                  href="#"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapseLayouts2"
                  aria-expanded="false"
                  aria-controls="collapseLayouts2"
                >
                  <div class="sb-nav-link-icon"><i class="fa-solid fa-circle-plus"></i></div>
                  Cadastro
                  <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div
                  class="collapse"
                  id="collapseLayouts2"
                  aria-labelledby="headingOne"
                  data-bs-parent="#sidenavAccordion"
                >
                  <nav class="sb-sidenav-menu-nested nav">
                    <a
                      class="nav-link {% if request.resolver_match and request.resolver_match.namespace == 'dashboard' and request.resolver_match.url_name == 'questoes' %}active{% endif %}"
                      href="{% url 'dashboard:questoes' %}"
                      >Questões</a
                    >
                    <a
                      class="nav-link {% if request.resolver_match and request.resolver_match.namespace == 'dashboard' and request.resolver_match.url_name == 'avaliacoes' %}active{% endif %}"
                      href="{% url 'dashboard:avaliacoes' %}"
                      >Avaliações</a
                    >
                    <a
                      class="nav-link {% if request.resolver_match and request.resolver_match.namespace == 'dashboard' and request.resolver_match.url_name == 'textos' %}active{% endif %}"
                      href="{% url 'dashboard:textos' %}"
                      >Textos de Apoio</a
                    >
                  </nav>
                </div>
                <a
                  class="nav-link {% if request.resolver_match and request.resolver_match.namespace == 'dashboard' and request.resolver_match.url_name == 'usuarios' %}active{% endif %}"
                  href="{% url 'dashboard:usuarios' %}"
                >
                  <div class="sb-nav-link-icon"><i class="fa-solid fa-user"></i></div>
                  Usuários
                </a>
                {% endif %}
                <!-- Menu Section -->
                <div class="sb-sidenav-menu-heading">Área do estudante</div>
                <a
                  class="nav-link {% if request.resolver_match and request.resolver_match.namespace == 'gabarita_if' and request.resolver_match.url_name == 'index' %}active{% endif %}"
                  href="{% url 'gabarita_if:index' %}"
                >
                  <div class="sb-nav-link-icon"><i class="fa-solid fa-house-chimney"></i></div>
                  Meu Painel
                </a>
                <a
                  class="nav-link {% if request.resolver_match and request.resolver_match.namespace == 'gabarita_if' and request.resolver_match.url_name == 'questoes' %}active{% endif %}"
                  href="{% url 'gabarita_if:questoes' %}"
                >
                  <div class="sb-nav-link-icon"><i class="fa-solid fa-bullseye"></i></div>
                  Questões
                </a>
                <a
                  class="nav-link {% if request.resolver_match and request.resolver_match.namespace == 'gabarita_if' and request.resolver_match.url_name == 'avaliacoes' %}active{% endif %}"
                  href="{% url 'gabarita_if:avaliacoes' %}"
                >
                  <div class="sb-nav-link-icon"><i class="fa-solid fa-book-open"></i></div>
                  Avaliações
                </a>
                <a
                  class="nav-link {% if request.resolver_match and request.resolver_match.namespace == 'gabarita_if' and request.resolver_match.url_name == 'cadernos' %}active{% endif %}"
                  href="{% url 'gabarita_if:cadernos' %}"
                >
                  <div class="sb-nav-link-icon"><i class="fa-solid fa-layer-group"></i></div>
                  Cadernos
                </a>
                <a
                  class="nav-link {% if request.resolver_match and request.resolver_match.namespace == 'gabarita_if' and request.resolver_match.url_name == 'meu-desempenho' %}active{% endif %}"
                  href="{% url 'gabarita_if:meu-desempenho' %}"
                >
                  <div class="sb-nav-link-icon"><i class="fa-solid fa-chart-pie"></i></div>
                  Meu Desempenho
                </a>
              </div>
            </div>
          </nav>
        </div>
        <div id="layoutSidenav_content">
          <main>{% block content %}{% endblock content %}</main>
        </div>
      </div>
    </div>

    <!-- modal -->
    <div class="modal" tabindex="-1">
      <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>Modal body text goes here.</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            <button type="button" class="btn btn-primary btn-salvar">Salvar</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Scripts -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      crossorigin="anonymous"
    ></script>
    <script>
      const mensagensUrl = "{% url 'dashboard:ajax-mensagens' %}";
      const questoesUrl = "{% url 'dashboard:ajax-questoes' %}";
    </script>
    <script src="{% static 'gabarita_if/js/scripts.js' %}"></script>
    <!-- Script da animação -->
    <script>
      document.addEventListener("DOMContentLoaded", function () {
        const splash = document.getElementById("splash-screen");
        const main = document.getElementById("main-content");

        setTimeout(() => {
          splash.classList.add("hide");
          setTimeout(() => {
            splash.style.display = "none";
            main.classList.add("show");
          }, 500); // tempo da transição
        }, 1500); // tempo de exibição inicial
      });
    </script>
    {% block scripts %}{% endblock %}
  </body>
</html>

templates/criar.html
{% load crispy_forms_filters %}
<section class="p-1">
  <div class="m-auto" style="max-width: 80rem">
    <form method="post" enctype="multipart/form-data" class="form-questao">
      <div class="card">
        <p>Campos com <span style="color: var(--danger-color)">*</span> são obrigatórios.</p>
        {% csrf_token %} 
        {% if partial_form %} 
        {% include partial_form %} 
        {% else %} 
        {{ form|crispy }} 
        {% endif %}
      </div>
    </form>
  </div>
</section>

templates/detalhar.html
{% load static %}
<section class="p-1">
  <div class="m-auto" style="max-width: 80rem">
    <div class="card">
      <div class="row">
        {% if perfil %}
        <div class="col-sm-4 text-center">
          <div class="profile-header-avatarAndEdit-wrapper w-100">
            <div class="profile-header-avatarAndEdit">
              {% if object.avatar %}
              <img
                class="profile-header-avatar rounded-circle"
                src="{{ object.avatar.url }}"
                alt="{{ object.username }}"
              />
              {% else %}
              <img
                class="profile-header-avatar rounded-circle"
                src="{% static 'assets/img/avatar.png' %}"
                alt="{{ object.username }}"
              />
              {% endif %}
            </div>
            <h5 class="profile-header-name">{{ object.username }}</h5>
            <p class="text-muted mb-0">{{ object.email }}</p>
          </div>
        </div>
        {% endif %}

        <div class="col">
          <div class="card-body">
            {% for field in fields %}
            <div class="row">
              <div class="col-sm-3 m-auto">
                <p class="mb-0 line-title">{{ field.label|capfirst }}</p>
              </div>
              <div class="col-sm-9">
                {% if field.many %}
                <p class="text-muted mb-0">
                  {% for item in field.value %} {{ item }}{% if not forloop.last %}, {% endif %} {% empty %}—{% endfor %}
                </p>
                {% else %} 
                {% if field.safe %}
                <p class="text-muted mb-0">{{ field.value|safe|default:"—" }}</p>
                {% else %}
                <p class="text-muted mb-0">{{ field.value|default:"—" }}</p>
                {% endif %} 
                {% endif %}
              </div>
            </div>
            {% if not forloop.last %}
            <hr />
            {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

templates/editar.html
{% load crispy_forms_filters %}
<section class="p-1">
  <div class="m-auto" style="max-width: 80rem">
    <form method="post" enctype="multipart/form-data" class="form-questao">
      <div class="card">
        <p>Campos com <span style="color: var(--danger-color)">*</span> são obrigatórios.</p>
        {% csrf_token %} 
        {% if partial_form %} 
        {% include partial_form %} 
        {% else %} 
        {{ form|crispy }} 
        {% endif %}
      </div>
    </form>
  </div>
</section>

templates/listar.html
{% extends "base.html" %} 
{% load static %}
{% block content %}
<header>
  <div class="m-auto" style="max-width: 80rem">
    <div class="d-flex align-items-center justify-content-between">
      <h1>{{ titulo_pagina }}</h1>
      {% if url_criar %}
      <a class="btn btn-primary btn-create btn-criar" href="{% url url_criar %}">Criar {{ nome }}</a>
      {% endif %}
    </div>
    <hr />
    <span>{{ subtitulo_pagina }}</span>
    {% if avaliacoes %}
    <ul class="nav nav-pills mt-3">
      <li class="nav-item">
        <a class="nav-link {% if tipo_selecionado == 'Prova' %}active{% endif %}" aria-current="page" href="?tipo=Prova">Provas</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if tipo_selecionado == 'Simulado' %}active{% endif %}" href="?tipo=Simulado">Simulados</a>
      </li>
    </ul>
    {% endif %}
  </div>
</header>
<section>
  <div class="m-auto" style="max-width: 80rem">
    {% if filtro %} {% include "gabarita_if/partials/_filtro.html" %} {% endif %} {% if objects %} {% include partial %}
    {% else %}
    <div class="card">
      <div
        class="card-body d-flex flex-column flex-md-row align-items-center justify-content-center gap-5 text-center text-md-start"
        style="margin: 5rem 0"
      >
        {% if url_criar %}
        <img src="{% static 'assets/img/3.png' %}" class="img-fluid" alt="" style="width: 15rem; max-width: 100%" />
        <div style="max-width: 20rem; word-wrap: break-word">
          <h5 class="fw-semibold mb-2">Ops, nada encontrado por aqui até o momento...</h5>
          <p class="m-0">Adicione um item para começar!</p>
          {% comment %} <a class="btn btn-primary btn-create btn-criar mt-4" href="{% url url_criar %}">Criar {{ nome }}</a> {% endcomment %}
        </div>
        {% else %}
        <img src="{% static 'assets/img/4.png' %}" class="img-fluid" alt="" style="width: 15rem; max-width: 100%" />
        <div style="max-width: 20rem; word-wrap: break-word">
          <h5 class="fw-semibold mb-2">Ops, parece que não há itens cadastrados!</h5>
          <p class="m-0">Aguarde até que um administrador adicione novos itens.</p>
        </div>
        {% endif %}
      </div>
    </div>
    {% endif %}
  </div>
</section>
{% endblock content %}

templates/remover.html
{% load static %}
<section class="p-1">
  <div class="d-flex justify-content-end" style="gap: 8px;">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Cancelar</a>
    <form method="post" class="form-remover">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger btn-confirmar">Remover</button>
    </form>
  </div>
</section>